window.PUZZLE_USB_IMPOSTER_WORDS = {
  "levels": [
    {
      "level": 1,
      "difficulty": "easy",
      "words": [
        "Sunflower",
        "Fruits",
        "Camera",
        "Liquid",
        "Book",
        "Ocean",
        "Apple",
        "Planet",
        "Baby",
        "Pail",
        "Cabbage",
        "Towel",
        "Eyeglasses",
        "Pumpkins",
        "Tree",
        "Breakfast",
        "Stairs",
        "White",
        "Stirrup",
        "Beach"
      ]
    },
    {
      "level": 2,
      "difficulty": "easy",
      "words": [
        "Berries",
        "Lemurs",
        "Knife",
        "Dessert",
        "Winter",
        "Flames",
        "Gymnastics",
        "Wedding",
        "Skates",
        "Pipe",
        "Peony",
        "Storm",
        "Chocolate",
        "Pineapple",
        "Cloud",
        "Glass",
        "Strawberry",
        "Mushrooms",
        "Broccoli",
        "Sun"
      ]
    },
    {
      "level": 3,
      "difficulty": "easy",
      "words": [
        "Straw",
        "Figurines",
        "Scarf",
        "Thought",
        "Wallet",
        "Hedgehog",
        "Window",
        "Vitamins",
        "Spices",
        "Groundnut",
        "Equilibrium",
        "Door",
        "Nebula",
        "Banana",
        "Smile",
        "Wheel",
        "Tea",
        "Bear",
        "Nautilus",
        "Tuber"
      ]
    },
    {
      "level": 4,
      "difficulty": "easy",
      "words": [
        "Lavender",
        "Snow",
        "Castle",
        "Police",
        "Knowledge",
        "Pizza",
        "Ink",
        "Bed",
        "Selfie",
        "Strings",
        "Eclipse",
        "Letter",
        "Tin",
        "Embers",
        "Balloon",
        "Foot",
        "Caviar",
        "Buffet",
        "Bunker",
        "Rock"
      ]
    },
    {
      "level": 5,
      "difficulty": "easy",
      "words": [
        "Antennas",
        "Blueberries",
        "Porcelain",
        "Spirit",
        "Apple",
        "Canyon",
        "Taxicab",
        "Reptile",
        "Shadow",
        "Overall",
        "Crown",
        "Atmosphere",
        "Insulator",
        "Show",
        "One",
        "Mammal",
        "Pieces",
        "Hay",
        "Reflection",
        "Water"
      ]
    },
    {
      "level": 6,
      "difficulty": "medium",
      "words": [
        "Bench",
        "Firewood",
        "Fuel",
        "Wind",
        "Persimmon",
        "Bird",
        "Tarmac",
        "Small",
        "Airport",
        "Baptism",
        "Cat",
        "Team",
        "Sheep",
        "Frost",
        "Speed",
        "Instrument",
        "Number",
        "Sloth",
        "Fork",
        "Honeymoon"
      ]
    },
    {
      "level": 7,
      "difficulty": "medium",
      "words": [
        "Wheelbarrow",
        "Grooming",
        "Feeding",
        "Geometry",
        "Trail",
        "Lighthouse",
        "Canvas",
        "Relaxation",
        "Silhouette",
        "Slope",
        "Pink",
        "Vacation",
        "Peel",
        "Scales",
        "Compass",
        "Time",
        "Net",
        "Cushions",
        "Basket",
        "Memories"
      ]
    },
    {
      "level": 8,
      "difficulty": "medium",
      "words": [
        "Plastic",
        "Fish",
        "Diamond",
        "Precious",
        "Cheese",
        "Seahorse",
        "Sack",
        "Finger",
        "Laser",
        "Salt",
        "Eyebrow",
        "Syrup",
        "Tomatoes",
        "Buddhism",
        "Sandwich",
        "Juice",
        "Policeman",
        "Sprinkler",
        "Hotel",
        "Hobby"
      ]
    },
    {
      "level": 9,
      "difficulty": "medium",
      "words": [
        "Strawberry",
        "Kiss",
        "Feet",
        "Waist",
        "Candle",
        "Trumpet",
        "Pond",
        "Exotic",
        "Landmark",
        "Green",
        "Bridge",
        "Clothes",
        "Root",
        "Flatiron",
        "Artichoke",
        "Fountain",
        "Atlas",
        "Christmas",
        "Eiffel",
        "Artist"
      ]
    },
    {
      "level": 10,
      "difficulty": "medium",
      "words": [
        "Supplies",
        "Dragonfly",
        "Pendulum",
        "Book",
        "Gift",
        "Vanilla",
        "Egypt",
        "Horse",
        "Two",
        "Mustard",
        "Puppy",
        "Pur\u00e9e",
        "Rust",
        "Stripes",
        "Stick",
        "Programming",
        "City",
        "Structure",
        "Heart",
        "Result"
      ]
    },
    {
      "level": 11,
      "difficulty": "hard",
      "words": [
        "Dragon",
        "Potter",
        "Predator",
        "Western",
        "Sky",
        "Roof",
        "Indoor",
        "Bite",
        "Spiral",
        "Ornithology",
        "Nest",
        "Carbohydrate",
        "Twin",
        "Wings",
        "Grass",
        "Seeds",
        "Chair",
        "Corset",
        "Signs",
        "Fruit"
      ]
    },
    {
      "level": 12,
      "difficulty": "hard",
      "words": [
        "Honeycomb",
        "Face",
        "Chain",
        "Sweet",
        "Stunt",
        "Back",
        "Agriculture",
        "Beans",
        "Sauce",
        "Knitting",
        "Waves",
        "Fur",
        "Transparency",
        "Aerial",
        "Square",
        "Tail",
        "Ferns",
        "Enclosure",
        "Cake",
        "White"
      ]
    },
    {
      "level": 13,
      "difficulty": "hard",
      "words": [
        "Tombstone",
        "Dress",
        "Windy",
        "Poppy",
        "Bread",
        "Turret",
        "Dough",
        "Studio",
        "Tasting",
        "Curls",
        "Crossed",
        "Lettuce",
        "Leaves",
        "Duck",
        "Organ",
        "Inheritance",
        "Latitude",
        "Dots",
        "Pollution",
        "Eye"
      ]
    },
    {
      "level": 14,
      "difficulty": "hard",
      "words": [
        "Lid",
        "Hand",
        "Game",
        "Toxic",
        "Vinyl",
        "Plate",
        "Damages",
        "Elements",
        "Open",
        "Repair",
        "Sushi",
        "Autumn",
        "Sun",
        "Tree",
        "Asian",
        "Kitchen",
        "Tamarind",
        "Poultry",
        "Cage",
        "Chess"
      ]
    },
    {
      "level": 15,
      "difficulty": "hard",
      "words": [
        "Headphones",
        "Apartment",
        "Pump",
        "Shoes",
        "Promise",
        "Puppet",
        "Quinoa",
        "Teeth",
        "Pillars",
        "Bear",
        "Cap",
        "Baby",
        "Lemon",
        "Floor",
        "Mask",
        "Beverage",
        "Almonds",
        "Vinegar",
        "Prayer",
        "Scavenger"
      ]
    },
    {
      "level": 16,
      "difficulty": "expert",
      "words": [
        "Preserve",
        "Butter",
        "Look",
        "Hero",
        "Music",
        "Harvesting",
        "Stroller",
        "Cheese",
        "Bus",
        "Cartoons",
        "Shoes",
        "Scent",
        "Ring",
        "Bracelet",
        "Owl",
        "Aisle",
        "Fishing",
        "Tooth",
        "Ivory",
        "Ball"
      ]
    },
    {
      "level": 17,
      "difficulty": "expert",
      "words": [
        "Hunter",
        "Camel",
        "Beanie",
        "Wool",
        "Horizon",
        "Empty",
        "Sandal",
        "Gloves",
        "Egg",
        "Balloon",
        "Elephant",
        "Chips",
        "Skin",
        "Crystal",
        "Train",
        "Belief",
        "Pasta",
        "Shed",
        "Whiskers",
        "Roof"
      ]
    },
    {
      "level": 18,
      "difficulty": "expert",
      "words": [
        "Florist",
        "Kitchen",
        "Stalactite",
        "Apple",
        "Russia",
        "Cherry",
        "Door",
        "Tomato",
        "Packaging",
        "Bakery",
        "Temperature",
        "Hair",
        "Souvenirs",
        "Pouring",
        "Fog",
        "Champagne",
        "Fig",
        "Harp",
        "Surf",
        "Rice"
      ]
    },
    {
      "level": 19,
      "difficulty": "expert",
      "words": [
        "Archive",
        "Macaron",
        "Insect",
        "Solo",
        "Horse",
        "Ribs",
        "Longship",
        "Rodent",
        "Thinking",
        "England",
        "Carrot",
        "Pocket",
        "Gnome",
        "Olive",
        "Capacitor",
        "Farm",
        "Childhood",
        "Copper",
        "Cross",
        "Kitchen"
      ]
    },
    {
      "level": 20,
      "difficulty": "expert",
      "words": [
        "Danger",
        "Future",
        "Mane",
        "Gymnastics",
        "Pattern",
        "Probability",
        "Professional",
        "Moon",
        "Hat",
        "Graffiti",
        "Cards",
        "Shorts",
        "Space",
        "Star",
        "Music",
        "Takeoff",
        "Surface",
        "Bird",
        "Tradition",
        "Visor"
      ]
    }
  ]
};
